---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен быть адаптивным к русскому и английскому языку с возможностью выбора языка
  - Цены на товар должны быть в долларах
  - Пользователь должен иметь возможность переходить на следующую и предыдущую страницы товаров вверху и внизу страницы
  - Кнопка "В корзину" должна быть синего цвета 
  - Актуальная цена товара должна быть красным цветом
  - Старая цена должна отображаться серым цветом и при этом быть зачеркнутой
  - Количество оставшихся позиций должно быть на главной странице с каждым товаром, отображается серым цветом
  - На главной странице иконка "Корзина" должна отображать количество позиций добавленных в корзину. Отображение позиций должно быть выделено лазурным цветом
  - Кнопка "Удалить" товар из корзины должна быть красного цвета
  - Кнопка "Оформить заказ" должна быть зелёного цвета
  - Кнопка "Очистить корзину" должна быть красного цвета
  - Кнопка "Продолжить покупки" товаров должна быть серого цвета
  - В корзине должна отображаться старая цена синим цветом и при этом быть зачеркнутой
  - В корзине отображение товара должно содержать - название товара/количество заказанных позиций/старая и новая цена. Содержимое должно быть синего цвета
